- name: reload nginx
  service: name=nginx state=reloaded
  become: true

# independent of flush handlers. BUG IMO.
- name: no really, reload nginx
  service: name=nginx state=reloaded
  become: true
